- name: Build and run matomo
  hosts: matomo
  connection: local
  gather_facts: no
  tasks:
    - docker_service:
        project_src: compose/x86
        state: absent

    - docker_service:
        project_name: compose/x86
        definition:
            remove_orphans: yes

      register: output

    - debug:
        var: output

    - assert:
        that:
          - "matomo.state.running"
