---

# Set up SSH keys on our machines.

- hosts: all
  tasks:
    - name: Add all SSH keys without removing previous ones
      authorized_key:
        user: root
        key: '{{ item }}'
      with_items:
        # the Guide team
        - https://github.com/willbasky.keys
        - https://github.com/avele.keys
        - https://github.com/kana-sama.keys 
        # the Codesearch team
        - https://github.com/Kabowyad.keys
        - https://github.com/kamilongus.keys
        - https://github.com/Evengining.keys
        - https://github.com/Som3.keys
        - https://github.com/ppressives.keys
        - https://github.com/lorof.keys
        # misc
        - https://github.com/neongreen.keys  # Artyom
