---

# Set up SSH keys on our machines.

- hosts: all
  tasks:
  - name: Add all SSH keys without removing previous ones
    authorized_key:
      user: root
      key: '{{ item }}'
    with_items:
      # Artyom
      - https://github.com/neongreen.keys
      # the Guide team
      - https://github.com/willbasky.keys
      - https://github.com/mixailflash.keys
      # the Codesearch team
      - https://github.com/Kabowyad.keys
      - https://github.com/kamilongus.keys
      - https://github.com/Evengining.keys
