#
# This playbook install docker, compose and keep it running. Then it fetch pointed in host image of guide from quay.io, run container, and start guide. And all of them will restarted if server rebooted.
# Launch sites on http not https.
#

- hosts: staging-guide
  become: true

  name: Install docker, compose and keep it running if they don't.
  pre_tasks:
    - include_role:
        name: geerlingguy.docker

  tasks:
    - name: Fetch image from quay.io and ensure a container is running.
      vars:
        - ansible_python_interpreter: "/usr/bin/env python-docker"
      docker_container:
        name: guide
        image: "quay.io/aelve/guide:{{image_name}}"
        pull: true
        state: started
        restart: true
        restart_policy: always
        command: "./guide"
        ports:
          - "{{guide_main_port}}:{{guide_main_port}}"
          - "{{guide_api_port}}:{{guide_api_port}}"
          - "{{guide_ekg_port}}:{{guide_ekg_port}}"
