# Using https://github.com/nickjj/ansible-docker/ to install docker

- hosts: stage
  become: true


  name: Install docker
  pre_tasks:
    - include_role:
        name: nickjj.docker
      vars:
        docker__edition: "ce"
        docker__channel: ["stable"]
        docker__version: ""
        docker__state: "latest"
        docker__compose_version: ""

    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: true
      changed_when: false

  tasks:
    - name: Fetch image from quay.io and ensure a container is running.
      vars:
        - ansible_python_interpreter: "/usr/bin/env python-docker"
      docker_container:
        name: guide
        image: "quay.io/aelve/guide:{{image_name}}"
        pull: true
        state: started
        restart: true
        restart_policy: always
        command: "./guide"
        ports:
          - "{{port_main}}:{{port_main}}"
          - "{{port_api}}:{{port_api}}"
          - "{{port_ekg}}:{{port_ekg}}"
