---

# Set up a load balancer and SSL terminator. All our domains should point to
# 'terminator', which reroutes traffic to the right machines.
#
# When adding a domain, don't forget to update both nginx_vhosts and
# certbot_certs.

- hosts: terminator
  tasks:

    - include_role:
        name: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: true
        nginx_upstreams:
          # Codesearch
          - name: codesearch
            servers: [ "s1.codesearch.aelve.com" ]
          - name: codesearch-portainer
            servers: [ "s1.codesearch.aelve.com:{{ codesearch_portainer_port }}" ]

          # Codesearch staging
          - name: codesearch-staging
            servers: [ "s1.staging.codesearch.aelve.com" ]
          - name: codesearch-staging-portainer
            servers: [ "s1.staging.codesearch.aelve.com:{{ codesearch_portainer_port }}" ]

          # Guide staging
          - name: guide-staging-front
            servers: [ "s1.staging.guide.aelve.com:{{ guide_front_port }}" ]
          - name: guide-staging-main
            servers: [ "s1.staging.guide.aelve.com:{{ guide_back_main_port }}" ]
          - name: guide-staging-api
            servers: [ "s1.staging.guide.aelve.com:{{ guide_back_api_port }}" ]
          - name: guide-staging-ekg
            servers: [ "s1.staging.guide.aelve.com:{{ guide_back_ekg_port }}" ]

        nginx_vhosts:
          # Codesearch
          - server_name: "codesearch.aelve.com"
            extra_parameters: |
              location / {
                proxy_pass http://codesearch;
              }
          - server_name: "codesearch.aelve.com"
            listen: "{{ codesearch_portainer_port }}"
            extra_parameters: |
              location / {
                proxy_pass http://codesearch-portainer;
              }

          # Codesearch staging
          - server_name: "staging.codesearch.aelve.com"
            extra_parameters: |
              location / {
                proxy_pass http://codesearch-staging;
              }
          - server_name: "staging.codesearch.aelve.com"
            listen: "{{ codesearch_portainer_port }}"
            extra_parameters: |
              location / {
                proxy_pass http://codesearch-staging-portainer;
              }

          # Guide staging
          - server_name: "staging.guide.aelve.com"
            extra_parameters: |
              location / {
                proxy_pass http://guide-staging-front;
              }
          - server_name: "staging.guide.aelve.com"
            listen: "{{ guide_back_main_port }}"
            extra_parameters: |
              location / {
                proxy_pass http://guide-staging-main;
              }
          - server_name: "staging.guide.aelve.com"
            listen: "{{ guide_back_api_port }}"
            extra_parameters: |
              location / {
                proxy_pass http://guide-staging-api;
              }
          - server_name: "staging.guide.aelve.com"
            listen: "{{ guide_back_ekg_port }}"
            extra_parameters: |
              location / {
                proxy_pass http://guide-staging-ekg;
              }

    - include_role:
        name: geerlingguy.certbot
      vars:
        certbot_admin_email: artyom@aelve.com
        certbot_certs:
          - domains:
              - codesearch.aelve.com
              - staging.codesearch.aelve.com
              - staging.guide.aelve.com
