---

# Set up a load balancer and SSL terminator. All our domains should point
# there and then traffic would be rerouted to the right machines.

# When adding a domain, don't forget to update both balancer_vhosts and
# certbot_certs.

- hosts: terminator
  tasks:

    - include_role:
        name: holms.balancer
      vars:
        balancer_vhosts:
          - { name: "codesearch.aelve.com", upstreams: ["s1.codesearch.aelve.com"] }
          - { name: "staging.codesearch.aelve.com", upstreams: ["s1.staging.codesearch.aelve.com"] }

    - include_role:
        name: geerlingguy.nginx
      vars:
        - nginx_upstreams:
            - name: guide-main
              strategy: "least_conn"
              servers: [
                "s1.staging.guide.aelve.com:{{ guide_main_port }} max_fails=1 fail_timeout=10s"
              ]

            - name: guide-api
              strategy: "least_conn"
              servers: [
                "s1.staging.guide.aelve.com:{{ guide_api_port }} max_fails=1 fail_timeout=10s"
              ]

            - name: guide-ekg
              strategy: "least_conn"
              servers: [
                "s1.staging.guide.aelve.com:{{ guide_ekg_port }} max_fails=1 fail_timeout=10s"
              ]

        - nginx_vhosts:
            # guide-main
            - listen: "{{ guide_main_port }} ssl"
              server_name: "staging.guide.aelve.com"
              error_page: "497 301 =307 https://$host:{{ guide_main_port }}$request_uri"
              state: "present"
              filename: "guide-main.conf"
              extra_parameters: |
                location / {
                    proxy_pass http://guide-main;
                    proxy_set_header Connection '';
                    proxy_set_header Host $http_host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    chunked_transfer_encoding off;
                    proxy_buffering off;
                    proxy_cache off;
                    client_max_body_size 200M;
                    }

                ssl_certificate /etc/letsencrypt/live/staging.guide.aelve.com/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/staging.guide.aelve.com/privkey.pem;
                include /etc/letsencrypt/options-ssl-nginx.conf;
                ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

            # guide-api
            - listen: "{{ guide_api_port }} ssl"
              server_name: "staging.guide.aelve.com"
              error_page: "497 301 =307 https://$host:{{ guide_api_port }}$request_uri"
              state: "present"
              filename: "guide-api.conf"
              extra_parameters: |
                location / {
                    proxy_pass http://guide-api;
                    proxy_set_header Connection '';
                    proxy_set_header Host $http_host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    chunked_transfer_encoding off;
                    proxy_buffering off;
                    proxy_cache off;
                    client_max_body_size 200M;
                    }

                ssl_certificate /etc/letsencrypt/live/staging.guide.aelve.com/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/staging.guide.aelve.com/privkey.pem;
                include /etc/letsencrypt/options-ssl-nginx.conf;
                ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

            # guide-ekg
            - listen: "{{ guide_ekg_port }} ssl"
              server_name: "staging.guide.aelve.com"
              error_page: "497 301 =307 https://$host:{{ guide_ekg_port }}$request_uri"
              state: "present"
              filename: "guide-ekg.conf"
              extra_parameters: |
                location / {
                    proxy_pass http://guide-ekg;
                    proxy_set_header Connection '';
                    proxy_set_header Host $http_host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    chunked_transfer_encoding off;
                    proxy_buffering off;
                    proxy_cache off;
                    client_max_body_size 200M;
                    }

                ssl_certificate /etc/letsencrypt/live/staging.guide.aelve.com/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/staging.guide.aelve.com/privkey.pem;
                include /etc/letsencrypt/options-ssl-nginx.conf;
                ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    - name: Install certbot-nginx
      apt:
        name: python-certbot-nginx
        update_cache: yes

    - include_role:
        name: geerlingguy.certbot
      vars:
        certbot_admin_email: yom@artyom.me
        certbot_certs:
          - domains:
              - codesearch.aelve.com
          - domains:
              - staging.codesearch.aelve.com
          - domains:
              - staging.guide.aelve.com
