---

# Set up a load balancer and SSL terminator. All our domains should point
# there and then traffic would be rerouted to the right machines.

# When adding a domain, don't forget to update both balancer_vhosts and
# certbot_certs.

# To certbot_certs's domains add server_name.

- hosts: terminator
  tasks:

    - include_role:
        name: holms.balancer
      vars:
        balancer_vhosts:
          - name: codesearch-portainer
            upstreams: [ 's1.staging.codesearch.aelve.com:{{ codesearch_portainer_port }}' ]
            listen_data: "{{ codesearch_portainer_port }} ssl"
            server_name: "staging.codesearch.aelve.com"
            error_page: "497 301 =307 https://$host:{{ codesearch_portainer_port }}$request_uri"

          - name: codesearch-staging
            upstreams: [ 's1.staging.codesearch.aelve.com' ]
            listen_data: "{{ codesearch_staging_port }} ssl"
            server_name: "staging.codesearch.aelve.com"
            error_page: "497 301 =307 https://$host$request_uri"

          - name: codesearch
            upstreams: [ 's1.codesearch.aelve.com' ]
            listen_data: "{{ codesearch_port }} ssl"
            server_name: "codesearch.aelve.com"
            error_page: "497 301 =307 https://$host$request_uri"

          - name: guide-main
            upstreams: [ 's1.staging.guide.aelve.com:{{guide_main_port}}' ]
            listen_data: "{{ guide_main_port }} ssl"
            server_name: "staging.guide.aelve.com"
            error_page: "497 301 =307 https://$host:{{ guide_main_port }}$request_uri"

          - name: guide-api
            upstreams: [ 's1.staging.guide.aelve.com:{{guide_api_port}}' ]
            listen_data: "{{ guide_api_port }} ssl"
            server_name: "staging.guide.aelve.com"
            error_page: "497 301 =307 https://$host:{{ guide_api_port }}$request_uri"

          - name: guide-ekg
            upstreams: [ 's1.staging.guide.aelve.com:{{guide_ekg_port}}' ]
            listen_data: "{{ guide_ekg_port }} ssl"
            server_name: "staging.guide.aelve.com"
            error_page: "497 301 =307 https://$host:{{ guide_ekg_port }}$request_uri"

    - include_role:
        name: geerlingguy.certbot
      vars:
        certbot_admin_email: yom@artyom.me
        certbot_certs:
          - domains:
              - codesearch.aelve.com
          - domains:
              - staging.codesearch.aelve.com
          - domains:
              - staging.guide.aelve.com
