---

# Modified as per <https://github.com/geerlingguy/ansible-role-certbot/pull/74/files>

- name: Ensure package repo is present
  apt_repository:
    repo: ppa:certbot/certbot
  when: ansible_distribution == "Ubuntu"

- name: Install Certbot.
  package: "name={{ certbot_package }} state=present"

- name: Install the Nginx plugin
  package: "name={{ certbot_package_nginx }} state=present"

# For some reason the config doesn't appear in /etc/letsencrypt
- name: Copy Nginx config
  copy:
    remote_src: yes
    src: /usr/lib/python3/dist-packages/certbot_nginx/options-ssl-nginx.conf
    dest: /etc/letsencrypt/options-ssl-nginx.conf

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "{{ certbot_package }}"
